[build]
command = "npm run build"
publish = "public"

[dev]
command = "npm run dev"
targetPort = 3000

[context.dev.environment]
  NODE_ENV = "development"
  SESSION_SECRET="foobar"
  PUBLIC_STOREFRONT_API_TOKEN="3b580e70970c4528da70c98e097c2fa0"
  PUBLIC_STOREFRONT_API_VERSION="2023-01"
  PUBLIC_STORE_DOMAIN="hydrogen-preview.myshopify.com"
